# Generated by Django 2.1 on 2018-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='billing_addr',
            field=models.CharField(default='Nigeria', max_length=500),
        ),
        migrations.AddField(
            model_name='billings',
            name='phone_number',
            field=models.IntegerField(default='91565616516516'),
        ),
        migrations.AddField(
            model_name='billings',
            name='pincode',
            field=models.IntegerField(default='5616166'),
        ),
        migrations.AddField(
            model_name='billings',
            name='shipping_addr',
            field=models.CharField(default='Nigeria', max_length=500),
        ),
    ]
