# Generated by Django 2.1 on 2018-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20181004_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='billing_addr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='billings',
            name='shipping_addr',
            field=models.CharField(max_length=500),
        ),
    ]
