# Generated by Django 2.1 on 2018-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20181004_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billings',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
