# Generated by Django 2.1 on 2018-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20181004_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/')),
                ('name_of_item', models.CharField(max_length=300)),
            ],
        ),
    ]
