# Generated by Django 2.1 on 2018-10-02 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uploaded_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
