# Generated by Django 2.1 on 2018-10-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_products_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='uploaded_at',
        ),
    ]
