# Generated by Django 2.1 on 2018-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20181003_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='item_type',
        ),
        migrations.AddField(
            model_name='products',
            name='items_type',
            field=models.CharField(choices=[('Bl', 'Blouse'), ('Sh', 'Shirt'), ('Sk', 'Skirt'), ('Gn', 'Gown')], default='Sk', max_length=1),
        ),
    ]
