# Generated by Django 2.1 on 2018-10-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_cart_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
    ]
