# Generated by Django 2.1 on 2018-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_auto_20181003_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
