# Generated by Django 2.1 on 2018-10-03 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_auto_20181003_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
