# Generated by Django 2.1 on 2018-10-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_billing_date_of_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/')),
                ('name_of_item', models.CharField(max_length=300)),
                ('desc_of_item', models.CharField(max_length=1000)),
                ('price_of_item', models.FloatField(default=19.99)),
            ],
        ),
    ]
