# Generated by Django 2.1 on 2018-10-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_auto_20181004_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='products',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
